server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5.0
    maxActive: 20.0
    maxWait: 60000.0
    minIdle: 5.0
    password: root
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
    username: root