spring:
  application:
    name: springboot-datasource-switch
api:
  boot:
    datasource:
      # 默认的数据源，默认值为master
      primary: master
      # 配置使用druid数据源
      druid:
        # master datasource config
        master:
          url: jdbc:mysql://127.0.0.1:3306/dataSource0?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: root
          # 默认值为【com.mysql.cj.jdbc.Driver】
          driver-class-name: com.mysql.cj.jdbc.Driver
          filters: stat,wall,slf4j
          max-active: 20
          initial-size: 1
          max-wait : 60000
          validation-query: select 1 from dual
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
        # slave 1
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/dataSource1?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: root
          # 默认值为【com.mysql.cj.jdbc.Driver】
          driver-class-name: com.mysql.cj.jdbc.Driver
          filters: stat,wall,slf4j
          max-active: 20
          initial-size: 1
          max-wait: 60000
          validation-query: select 1 from dual
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
        # slave 2
        slave_2:
          url: jdbc:mysql://127.0.0.1:3306/dataSource2?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: root
          # 默认值为【com.mysql.cj.jdbc.Driver】
          driver-class-name: com.mysql.cj.jdbc.Driver
          filters: stat,wall,slf4j
          max-active: 20
          initial-size: 1
          max-wait: 60000
          validation-query: select 1 from dual
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false


# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  mybatis.type-aliases-package: com.my.datasource.domain

